---
dependency:
  name: galaxy
driver:
  name: default
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos7
    image: centos:7
    dockerfile: ../resources/Dockerfile.j2
    # pre_build_image: true
    command: /usr/sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: wheel
      DEPLOY_GROUP: deployer
      container: docker
provisioner:
  name: ansible
verifier:
  name: ansible

